server:
  port: 4949


spring:
  datasource:
#    url: jdbc:mysql://3ig3294254.zicp.fun:42639/ry_vue?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&characterEncoding=utf8
    url: jdbc:mysql://localhost:3306/ry_vue?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&characterEncoding=utf8
    username: gongyu
    password: wtxf4949
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.qq.com
    username: q7800067@qq.com
    password: hcdbpzpjobdqbhhe
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false

#mybatis-plus:
#  mapper-locations: classpath:mapper/**/**Mapper.xml

mybatisNoSpringMappersLocation: invest.lixinger.ruoyi.mapper