# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.8.3
  # 版权年份
  copyrightYear: 2022
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/ruoyi/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  # connectionTimeout: 180000000
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles: 
    active: druid
  # 文件上传
  servlet:
     multipart:
       # location: /tmp/undertow
       # 单个文件大小
       max-file-size:  1024MB
       # 设置总上传的文件大小
       max-request-size:  2048MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # redis 配置
# 正式
  redis:
    # 地址
    host: 10.0.24.3
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 5
    # 密码
    password: 123456
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# 本地
#  redis:
#    # 地址
#    host: 124.223.63.81
#    # 端口，默认为6379
#    port: 6379
#    # 数据库索引
#    database: 5
#    # 密码
#    password: 3.141592653
#    # 连接超时时间
#    timeout: 10s
#    lettuce:
#      pool:
#        # 连接池中的最小空闲连接
#        min-idle: 0
#        # 连接池中的最大空闲连接
#        max-idle: 8
#        # 连接池的最大数据库连接数
#        max-active: 8
#        # #连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1ms



# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌密钥
    secret: abcdefghijklmnopqrstuvwxyz
    # 令牌有效期（默认30分钟）
    expireTime: 120

  # token配置
app:
  token:
    # 令牌自定义标识
    header: Authorization
    # 令牌密钥
    secret: appabcdefghijklmnopqrstuvwxyz
    # 令牌有效期（默认7天 60*60*24*7）单位s
    expireTime: 604800
  filter:
    urls: /app/user/bindPhone,app/api/wechatPay/v3/wechatPay,/app/wxPay/**,/app/*/order/**,/app/gauge/result,/app/gauge/result/commit,/app/gauge/questions/list,/app/home/gauge/getInfo,/app/course/getInfo,/app/course/detail*,/app/course/section/list,/app/course/userSection/saveUserSectionInfo,/app/course/getCourseListByUserId*
  
# MyBatis配置
#mybatis:
#    # 搜索指定包别名
#    typeAliasesPackage: com.ruoyi.**.domain
#    # 配置mapper的扫描，找到所有的mapper.xml映射文件
#    mapperLocations: classpath*:mapper/**/*Mapper.xml
#    # 加载全局的配置文件
#    configLocation: classpath:mybatis/mybatis-config.xml

# MyBatis Plus配置
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.ruoyi.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
#  configLocation: classpath:mybatis/mybatis-config.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: ASSIGN_ID
      # 默认数据库表下划线命名
      table-underline: true
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

# PageHelper分页插件
pagehelper: 
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql 

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

#springboot集成短信
#访问阿里云API的验证
aliyun:
  sms:
    accessKeyId: LTAI4GJMgXT6x4Diu7zZTKfJ
    #访问阿里云API的验证
    accessKeySecret: 8cXiAMIErHUZwaOdogBp9LLn2BgeoR
    #    accessKeySecret: lx65xmXfYLJObT66LfQrIOuzvlrcid
    #阿里云云通信短信API产品
    product: Dysmaspi
    #产品域名
    domain: dysmsapi.aliyuncs.com
    #签名
    signName: echo智能客服
    #发送验证码模版CODE
    templateCode: SMS_202813583

cos:
  secretId: AKIDe8NM9oEYHlyud5JK5cuzotjIchaIk5B3
  secretKey: sXHo43lDQN7amjPE0dBpHWWIsDJAsMba
  appId: 1316267898
  bucket: ssg-1316267898
  zxBucket: zx-1316267898
  gaugeBucket: gauge-1316267898

# 正式
#wx:
#  login:
#    appId: wx81f97b38440a3b86
#    appSecret: f259b9c0951de86bcfda3e482e7b3c45
#    redirectUri: http://127.0.0.1:8089/pages/logincallback

#开发
#wx:
#  login:
#    appId: wx8604d98104f67e66
#    appSecret: 98dca366602a0806da390ed138e4a7ea
#    redirectUri: http://192.168.137.215:8080/pages/logincallback

# 正式公众号
wx:
  login:
    appId: wx9891e2d78c14ef94
    appSecret: daf7d8f1b2033493921f0731dc0a2876
    redirectUri: http://wx.ssgpsy.com/pages/logincallback

#测试
#wx:
#  login:
#    appId: wxb973c5107125a24b
#    appSecret: ad2c1dd102b31f8d6ac942882180ae71
#    redirectUri: http://192.168.137.1:8081/pages/logincallback