# Spring配置
spring:
  # 指定加载哪个配置文件
  profiles:
    active: dev,druid-dev
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 邮箱配置
  mail:
    host: smtp.qq.com
    username: yoki1997@qq.com
    password: zspzjqohijpydeaj
    default-encoding: utf-8
    protocol: smtp
    port: 465
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          ssl:
            enable: true
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: ${config.server.port}
  servlet:
    # 应用的访问路径
    context-path: ${config.server.context-path}
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100
# mybatisPlus 配置
mybatis-plus:
  type-aliases-package: com.onethinker.**.domain,com.onethinker.**.dto
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml
# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql
# Swagger配置
swagger:
  # 是否开启swagger
  enabled: ${config.swagger.enabled}
  # 请求前缀
  pathMapping: ${config.server.context-path}
# 项目相关配置
onethinker:
  # 作者信息
  auth:
    name: 杨友奇
    url: https://gitee.com/yangyouqi
    email: yoki1997@qq.com
  # 名称
  name: onethinker
  # 版本
  version: 1.0.1
  # 文件路径 示例（ Windows配置D:/onethinker/uploadPath，Linux配置 /home/onethinker/uploadPath）
  profile: ${config.profile.basePath}
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math
  #文件存储配置，不使用的情况下可以不写
  file-storage:
    #水印配置
    waterMark:
      enabled: true
    #允许的文件后缀 不写默认全部允许
    allow-extension:
    #允许的文件类型 不写默认全部允许
    allow-mime:
    #默认使用的存储平台
    default-platform: ${config.file-storage.default-platform}
    # 本地存储
    local:
      # 存储平台标识
      platform: local
      # 启用存储
      enable-storage: true
      # 文件路径
      base-path: ${config.profile.basePath}
      # 访问域名
      domain: ${config.file-storage.local.domain}
    # 腾讯云 COS
    tencent-cos:
      # 存储平台标识
      platform: tencent
      # 启用存储
      enable-storage: true
      secret-id: ${config.file-storage.tencent-cos.secret-id}
      secret-key: ${config.file-storage.tencent-cos.secret-key}
      #存仓库所在地域
      region: ${config.file-storage.tencent-cos.region}
      # 令牌桶名称
      bucket-name: ${config.file-storage.tencent-cos.bucket-name}
      # 访问域名
      domain: 'https://cos-iops-1258646189.cos.ap-guangzhou.myqcloud.com/'
      # 基础路径
      base-path: ${config.profile.basePath}
    # 华为云 OBS ，不使用的情况下可以不写
    huawei-obs:
      # 存储平台标识
      platform: huawei
      # 启用存储
      enable-storage: true
      access-key: ${config.file-storage.huawei-obs.access-key}
      secret-key: ${config.file-storage.huawei-obs.secret-key}
      end-point: ${config.file-storage.huawei-obs.end-point}
      bucket-name: ${config.file-storage.huawei-obs.bucket-name}
      # 访问域名
      domain: 'https://obs-iops.obs.cn-east-3.myhuaweicloud.com'
      # 基础路径
      base-path: ${config.profile.basePath}
  # 用户配置
  user:
    password:
      # 密码最大错误次数
      maxRetryCount: 5
      # 密码锁定时间（默认10分钟）
      lockTime: 10
  # token配置
  token:
    # 令牌自定义标识
    header: Authorization
    # 令牌密钥
    secret: ${config.token.secret}
    # 令牌有效期（默认30分钟）
    expireTime: ${config.token.expireTime}
  # 防止XSS攻击
  xss:
    # 过滤开关
    enabled: true
    # 排除链接（多个用逗号分隔）
    excludes: /system/notice
    # 匹配链接
    urlPatterns: /system/*,/monitor/*,/tool/*