# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 18081
  servlet:
    # 应用的访问路径
    context-path: /ywkj-be
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100
# 日志配置
logging:
  level:
    com.onethinker: debug
    org.springframework: warn
# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: 114.132.69.190
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: 123456
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  # 邮箱配置
  mail:
    host: smtp.qq.com
    username: yoki1997@qq.com
    password: zspzjqohijpydeaj
    default-encoding: utf-8
    protocol: smtp
    port: 465
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          ssl:
            enable: true
# mybatisPlus 配置
mybatis-plus:
  type-aliases-package: com.**.**.domain
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml
# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql
# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api
# 项目相关配置
onethinker:
  # 名称
  name: onethinker
  # 版本
  version: 3.8.6
  # 版权年份
  copyrightYear: 2024
  # 文件路径 示例（ Windows配置D:/onethinker/uploadPath，Linux配置 /home/onethinker/uploadPath）
  profile: /onethinker/public/ywkj
  # 获取ip地址开关
  addressEnabled: true
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math
  #文件存储配置，不使用的情况下可以不写
  file-storage:
    #水印配置
    waterMark:
      enabled: true
    #允许的文件后缀 不写默认全部允许
    allow-extension:
    #允许的文件类型 不写默认全部允许
    allow-mime:
    #默认使用的存储平台
    default-platform: local
    # 本地存储
    local:
      # 存储平台标识
      platform: local
      # 文件路径
      base-path: /onethinker/public/ywkj
      # 访问域名
      domain: http://127.0.0.1:18081/
    # 腾讯云 COS
    tencent-cos:
      # 存储平台标识
      platform: tencent
      # 启用存储
      enable-storage: true
      secret-id: 'AKIDDskl0ELH1jJoFXn7OxdkqJoEUjMcrtpq'
      secret-key: 'SrM1fZPSfkijoz2AJZqBRaozxoYClKtV'
      #存仓库所在地域
      region: 'ap-guangzhou'
      # 令牌桶名称
      bucket-name: 'cos-iops-1258646189'
      # 访问域名，注意“/”结尾，例如：https://abc.cos.ap-nanjing.myqcloud.com/
      domain: 'https://cos-iops-1258646189.cos.ap-guangzhou.myqcloud.com/'
      # 基础路径
      base-path: iops
    # 华为云 OBS ，不使用的情况下可以不写
    huawei-obs:
      # 存储平台标识
      platform: huawei
      # 启用存储
      enable-storage: false
      access-key: 'T3FOARI4F8K8MOHWG49F'
      secret-key: 'ZDnNl3SzvHb5wJubf4xPX6ro5oecsLF9aKy8y9td'
      end-point: 'obs.cn-east-3.myhuaweicloud.com'
      bucket-name: 'obs-iops'
      # 访问域名，注意“/”结尾，例如：http://abc.obs.com/
      domain: 'https://obs-iops.obs.cn-east-3.myhuaweicloud.com'
      # 基础路径
      base-path: iops
    #阿里云 OSS
    aliyun-oss:
      # 存储平台标识
      platform: aliyun
      base-path: /home
    #七牛云 kodo
    qiniu-kodo:
      # 存储平台标识
      platform: qiniu
      base-path: /home
    # 百度云 BOS
    baidu-bos:
      # 存储平台标识
      platform: baidu
      base-path: /home
  sms-storage:
    # 腾讯云 COS
    tencent-sms:
      # 存储平台标识
      platform: tencent
      # 启用下发
      enable-storage: true
      secret-id: 'AKIDDskl0ELH1jJoFXn7OxdkqJoEUjMcrtpq'
      secret-key: 'SrM1fZPSfkijoz2AJZqBRaozxoYClKtV'
  # 用户配置
  user:
    password:
      # 密码最大错误次数
      maxRetryCount: 5
      # 密码锁定时间（默认10分钟）
      lockTime: 10
  # token配置
  token:
    # 令牌自定义标识
    header: Authorization
    # 令牌密钥
    secret: abcdefghijklmnopqrstuvwxyz
    # 令牌有效期（默认30分钟）
    expireTime: 30
  # 防止XSS攻击
  xss:
    # 过滤开关
    enabled: true
    # 排除链接（多个用逗号分隔）
    excludes: /system/notice
    # 匹配链接
    urlPatterns: /system/*,/monitor/*,/tool/*